### ISSUE TITLE
"Cannot GET /" 

### ISSUE THREAD

**Issue by KenLiu2018** [IBM-Cloud/cloud-event-management-sample#5]
Dears,
I followed the instruction to install the APP in Bluemix and Locally. 
However, when I opened the url, it returned "Cannot GET /" . Neither bluemix URL nor localhost url worked.

kens-mbp:$ cf apps
Getting apps in org XXX / space XXX as XXX
OK
name           requested state   instances   memory   disk   urls
CEMSampleApp   started           1/1         256M     1G     cemsampleapp-funny-meerkat.mybluemix.net

kens-mbp:$ ./run.sh
> cem-starter-app@0.0.2 start /Users/Ken/cloud-event-management-sample/src
> node --max-old-space-size=256 bin/www
Integration broker server started on http://localhost:6001/api/broker

Does anyone know what's going one? Thanks.

**Comment by bfabec** [comment]
Hi @KenLiu2018 - sorry for LONG delay.

If you go to http://localhost:6001/api/broker/v1/catalog you should get back the catalog. Let me know if you have more problems.
